_data/navigation.yml, _for-parents/School Booklist.md, _pcps-personnel/Non–Teaching Staff.md, _pcps-personnel/Teaching Staff.md
Dear Adrian, 
Please approve my Pull Request for our school website.
=> Please Approve

_about-pcps/Principal's Message.md
Hi Adrian,
For your approval please.
Thank you.
=> update on 22 may 2023

_for-parents/Parents Notes/2023.md, resources/news-and-announcements/_posts/2023-07-06-link-ENHANCED EDUSAVE AND MOE FAS AND REVISED MISCELLANEOUS FEES STRUCTURE FROM 2024.md
Hi Adrian,
For your approval, please.
Thank you.
=> PG Updated 07/07/2023

_about-pcps/School Leaders.md, _for-parents/Parents Notes/2023.md, resources/news-and-announcements/_posts/2023-07-06-link-ENHANCED EDUSAVE AND MOE FAS AND REVISED MISCELLANEOUS FEES STRUCTURE FROM 2024.md
Hi Adrian,
For your approval, please.
Thank you.
=> Updated on Ms Thia's content

_about-pcps/School Leaders.md, _for-parents/Home Based Learning/Home–Based Learning.md, _for-parents/Parents Notes/2023.md, _for-parents/Subject Downloads/ICT Connect @ Cove.md, _pcps-personnel/Learning Support Staff.md, _pcps-personnel/School Executive Committee.md, _pcps-personnel/Teaching Staff.md, resources/news-and-announcements/_posts/2023-07-06-link-ENHANCED EDUSAVE AND MOE FAS AND REVISED MISCELLANEOUS FEES STRUCTURE FROM 2024.md
Hi Adrian,
For your approval, please.
Thank you.
=> Webpages Updated

_for-parents/Forms.md, _mk-at-punggol-cove/Staff Contact List.md, index.md
Hi Adrian,
For your approval, please.
1. Request by Adelena: To update the Waitlist link, Done.
2. Reques by Jesslyn: To update the MK Staff List, Done.
Thank you.
=> 15/08/2023 School Website Update

_data/navigation.yml, index.md
=> 18 August 2023

_english-spelling-test/Primary 2.md, _for-parents/Parents Notes/2023.md, resources/news-and-announcements/_posts/2023-09-27-link-SCHOOL HEALTH VISIT 2023.md
Hi Adrian,
For your approval please.
=> 29 September 2023

index.md
i have removed the for teachers link.
=> Thursday 8 feb 2024

_about-pcps/Our People/Teaching Staff.md
=> Teaching Staff Updated

_about-pcps/Our People/Teaching Staff.md
=> 1R Teacher updated

_english-spelling-list/Primary 1.md, _english-spelling-list/Primary 2.md, _english-spelling-list/Primary 3.md, _english-spelling-list/Primary 4.md, _english-spelling-list/Primary 5 Foundation English.md, _english-spelling-list/Primary 5 Standard English.md
=> Quizlet Updated

_data/footer.yml
Dear Chow Ching and Adrian,
For your approval, please. 
Thank you.
=> Updated School Official Social Media Page

_mk-at-punggol-cove/Our Staff/Staff List and Email Address.md
=> MK Staff Lists Updated

_mk-at-punggol-cove/Enrol Your Child With Us.md
Dear Chow Ching, for your approval please. Thank you.
=> Made changes in MK Website on the Waitlist portion

_mk-at-punggol-cove/Our People/Staff List and Email Address.md, _mk-at-punggol-cove/Our Vision, Mission & Belief.md
=> mk website update

_pcps-partners/For Parents/Communication with Parents.md
=> ICT Connect Updated

_about-pcps/Our People/Teaching Staff.md
Dear Adrian, for your approval please. Thank you.
=> PCPS teachers staff lists updated.

_about-pcps/Our People/Learning Support Staff.md, _about-pcps/Our People/Non–Teaching Staff.md, _about-pcps/Our People/School Executive Committee.md, _about-pcps/Our People/Support Staff.md, _about-pcps/Our People/Teaching Staff.md
Dear Adrian, for your approval please. Thank you.
=> PCPS Staff Lists updated

_about-pcps/Our People/School Executive Committee.md, _about-pcps/Our People/Teaching Staff.md
for your approval please. thank you.
=> pcps staff list updated

_about-pcps/Principal's Message.md
For your approval please. Thank you.
=> Principal's message

_about-pcps/Our People/Teaching Staff.md, _pcps-partners/For Parents/Communication with Parents.md
=> Email Address links updated
